// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.2 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7STQU/cTgzFv8rIJ5DCBv7/W1APtHvJoaIiRRwqDsPEmzVKZsLYSUWjfPfKCaGwu0IU",
	"qafdTJz3bL/fDOBC0waPXhiyYUyA/CZANoCQ1AgZbK3llBpbka9OWLryERLoMTIFD9nyz/gghlFgTCC0",
	"6G1LkMH/q9PVGSTQWtmqPKT9WRpiZT39skLBczq8fMzXY6oWhFN1G1j0t0R2kVqZHQsJEU3uWax3yObi",
	"W25Yz9is8y+XXw09v7LMwZEVLM1Pkq2Z2n9+bzpPDx0aKtELbQgjm6PiOl8fr2CaIs5NlYvps+c0UrQN",
	"CkaG7McApJ3pmJCAt40u7vVgkEDEh44ilpBJ7DABdlts7LTrx1a/YInkKxjH27kYWT6H8lErXPCCftqG",
	"bdua3CSbluRCo4d/tDYhNlYggzvyNmpYu+rjbivTAbfB87z3/05P3/C8Z41h2G8/3N2jk9ngdWQXhjvn",
	"kHnT1WaxWoEWctc02uZ+rkfF98ubk6viWEewle4Z8pnDQnMsMPbkEG5V5v1gpcNEweJzna9HnaHCA6hd",
	"oUTCHs1kOJEWUbro2di6fgGa0kXeyBZNRT36mbR9jBbB4uke/VOKkoOCu9P/PZhvktJ0tVBro6QRa715",
	"50ZFPu1Re/4BbD9A1U6ERzcX68v3QaUyGPslmy7WkEEKuoOnL4dlp4cUxtvxdwAAAP//aO6xqF0FAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
