// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.2 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7STQU/bQBCF/8pqTiCZGNqbUQ+0ufhQUeEiDhWHZT1xBtm7Zmfsilr+79XYmEKIqhSp",
	"pyS7s/PmzfsygAtNGzx6YciGMQHymwDZAEJSI2SwtZZTamxFvjph6cpHSKDHyBQ8ZMs344MYRoExgdCi",
	"ty1BBh9Xp6szSKC1stX2kPZnaYiV9fTLCgXP6fDyZ74eU5UgnKrbwKKfJbKL1MqsWEiIaHLPYr1DNhff",
	"csN6xmadf7n8auj5yjIHR1awND9JtmYa//nedJ4eOjRUohfaEEY2R8V1vj5eweQizkOVi+iz5mQp2gYF",
	"I0P2YwDSydQmJOBto4t7bQwSiPjQUcQSMokdJsBui42ddv3Y6guWSL6Ccbydi5HlcygftcIFL+inbTRd",
	"LdTaKGnEWr2dG33/ybZtTW6SS0tyodHiPxqbEBsrkMEdeRs1xF3VcXfE6YDb4HnO48Pp6c4sLzXvWeMZ",
	"3toKd/foZBZ4HeWF4c45ZN50tVmkVqCF3DWNjvk276Pi++XNyVVxrBZspfuHfOaz0HwLjD05hFttczhw",
	"6TDRsehc5+tRPVS4B8ErlEjYo5kEJwIjShc9G1vXLwBU6sgb2aKpqEc/E/gWr6Vh8fT/+q90JXsb7rr/",
	"d2D/SsrB1J6/A9t3ULUT4dHNxfryMKi0DcZ+yaaLNWSQgu7g6eWw7HRfh/F2/B0AAP//urRa0HUFAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
