// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.2 DO NOT EDIT.
package openapi

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// ImagingStudyServiceStoreInstancesMultipartBody defines parameters for ImagingStudyServiceStoreInstances.
type ImagingStudyServiceStoreInstancesMultipartBody = openapi_types.File

// ImagingStudyServiceStoreInstancesMultipartRequestBody defines body for ImagingStudyServiceStoreInstances for multipart/related; type=application/dicom ContentType.
type ImagingStudyServiceStoreInstancesMultipartRequestBody = ImagingStudyServiceStoreInstancesMultipartBody
