// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.2 DO NOT EDIT.
package openapi

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// StoreInstancesMultipartBody defines parameters for StoreInstances.
type StoreInstancesMultipartBody = openapi_types.File

// StoreInstancesMultipartRequestBody defines body for StoreInstances for multipart/related; type=application/dicom ContentType.
type StoreInstancesMultipartRequestBody = StoreInstancesMultipartBody
