version: '3.8'

services:
  imaging-study:
    build:
      context: .
      dockerfile: docker/local.Dockerfile
    command: "air -c air.toml"
    volumes:
      - ./src:/go/src/github.com/mnes/haas/src
      - ./dev-support/shared/secrets/dev:/go/dev-support
    working_dir: /go/src/github.com/mnes/haas/src/services/imaging-study
    env_file:
      - .env
    ports:
      - 8080:8080