openapi: 3.0.1
info:
  title: haas/organization/organization.proto
  version: version not set
servers:
- url: /
tags:
- name: OrganizationService
paths:
  /v1/organizations:
    post:
      tags:
      - OrganizationService
      summary: 組織の作成
      operationId: OrganizationService_CreateOrganization
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/organizationCreateOrganizationRequest'
        required: true
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/organizationOrganization'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      x-codegen-request-body-name: body
  /v1/organizations/{organizationId}:
    get:
      tags:
      - OrganizationService
      summary: 組織の取得
      operationId: OrganizationService_GetOrganization
      parameters:
      - name: organizationId
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/organizationOrganization'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
    put:
      tags:
      - OrganizationService
      summary: 組織の更新
      operationId: OrganizationService_UpdateOrganization
      parameters:
      - name: organizationId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                active:
                  type: boolean
                name:
                  type: string
        required: true
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/organizationOrganization'
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
      x-codegen-request-body-name: body
    delete:
      tags:
      - OrganizationService
      summary: 組織の削除
      operationId: OrganizationService_DeleteOrganization
      parameters:
      - name: organizationId
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
components:
  schemas:
    organizationCreateOrganizationRequest:
      type: object
      properties:
        name:
          type: string
        active:
          type: boolean
    organizationOrganization:
      type: object
      properties:
        organizationId:
          type: string
        active:
          type: boolean
        name:
          type: string
    protobufAny:
      type: object
      properties:
        '@type':
          type: string
      additionalProperties:
        type: object
    rpcStatus:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/protobufAny'
