// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.2 DO NOT EDIT.
package openapi

// CreateDicomStoreJSONBody defines parameters for CreateDicomStore.
type CreateDicomStoreJSONBody struct {
	DatasetID    string `json:"datasetID"`
	DicomStoreID string `json:"dicomStoreID"`
}

// CreateDicomStoreJSONRequestBody defines body for CreateDicomStore for application/json ContentType.
type CreateDicomStoreJSONRequestBody CreateDicomStoreJSONBody
