openapi: 3.0.1
info:
  title: Imaging-Study API Reference
  description: |
    LOOKREC Andromeda - Imaging-Study APIは、RESTを中心に構成されています。
  version: version not set
servers:
- url: http://localhost:8080
  description: ローカル開発用
- url: https://andromeda.lookrec.com
  description: 本番サーバー
paths:
# Datasets - データセット
  /v1/organizations/{organizationID}/dataset:
    post:
      tags:
      - Datasets - データセット
      summary: Create a new Dataset
      description: |
        組織内に医療データを保管するためのデータセットを作成することができます。  
        DICOMStoreを作成するためには、先にデータセットを作成する必要があります。
      parameters:
        - name: organizationID
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_dataset_request'
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/create_dataset_response'
  
  /v1/organizations/{organizationID}/datasets:
    get:
      tags:
      - Datasets - データセット
      summary: Returns a list of your Datasets.
      description: |
        組織内に作成済みデータセットのリストを取得します
      parameters:
        - name: organizationID
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list_dataset_response'
  
  /v1/organizations/{organizationID}/datasets/{datasetID}:
    delete:
      tags:
      - Datasets - データセット
      summary: Delete the Dataset with the given ID.
      description: |
        組織内に作成済みデータセットを削除することができます。  
        データセットに紐付くDICOMStoreがある場合はそちらも削除されます
      parameters:
        - name: organizationID
          in: path
          required: true
          schema:
            type: string
        - name: datasetID
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: The resource was deleted successfully.

# DICOMStore - DICOMストア
  /v1/organizations/{organizationID}/dicomStore:
    post:
      tags:
      - DICOMStore - DICOMストア
      summary: Create a DicomStore
      description: |
        組織内のデータセット内DICOMStoreを作成します
        検査画像を保管するためには、先にDICOMStoreを作成する必要があります。
      parameters:
        - name: organizationID
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create_dicomstore_request'
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/create_dicomstore_response'
  
  /v1/organizations/{organizationID}/datasets/{datasetID}/dicomStores:
    get:
      tags:
      - DICOMStore - DICOMストア
      summary: Returns a list of your DICOMStores.
      description: |
        組織内のデータセット内に作成済みDICOMStoreのリストを取得します
      parameters:
        - name: organizationID
          in: path
          required: true
          schema:
            type: string
        - name: datasetID
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/list_dicomstore_response'
  
  /v1/organizations/{organizationID}/datasets/{datasetID}/dicomStores/{dicomStoreID}:
    delete:
      tags:
      - DICOMStore - DICOMストア
      summary: Delete the Dataset with the given ID.
      description: |
        組織内のデータセット内に作成済みDICOMStoreを削除することができます。  
        DICOMStoreに検査画像が保管されている場合はすべて削除されます
      parameters:
        - name: organizationID
          in: path
          required: true
          schema:
            type: string
        - name: datasetID
          in: path
          required: true
          schema:
            type: string
        - name: dicomStoreID
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: The resource was deleted successfully.

# ImagingStudies - 検査画像(DICOM)
  /v1/organizations/{organizationID}/studies:
    post:
      tags:
      - ImagingStudies - 検査画像(DICOM)
      summary: Store Instances (STOW-RS)
      description: |
        1件以上のDICOM画像をStudyInstanceUIDに基づいて保管することができます
      parameters:
      - name: organizationID
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/dicom:
            schema:
              $ref: '#/components/schemas/store_instances_request'
        required: true
      responses:
        200:
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/store_instances_response'

  /v1/organizations/{organizationID}/studies/{studyInstanceUID}:
    get:
      tags:
      - ImagingStudies - 検査画像(DICOM)
      summary: Retrieve Study (WADO-RS)
      description: |
        StudyInstanceUIDに基づいてすべてのDICOM画像を取得することができます
      operationId: RetrieveStudy
      parameters:
      - name: organizationID
        in: path
        required: true
        schema:
          type: string
      - name: studyInstanceUID
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: A successful response.
          content:
            multipart/related; type=application/dicom;:
              schema:
                $ref: '#/components/schemas/retrieve_study_response'

components:
  schemas:
    create_dataset_request:
      type: object
      properties:
        datasetID:
          type: string
    
    create_dataset_response:
      type: object
      properties:
        organizationID:
          type: string
        datasetID:
          type: string
    
    list_dataset_response:
      type: array
      items:
        type: object
        properties:
          organizationID:
            type: string
          datasetID:
            type: string
      
    create_dicomstore_request:
      type: object
      properties:
        datasetID:
          type: string
        dicomStoreID:
          type: string
      required:
        - datasetID
        - dicomStoreID
    
    create_dicomstore_response:
      type: object
      properties:
        organizationID:
          type: string
        datasetID:
          type: string
        dicomStoreID:
          type: string

    list_dicomstore_response:
      type: array
      items:
        type: object
        properties:
          organizationID:
            type: string
          datasetID:
            type: string
          dicomStoreID:
            type: string
    
    store_instances_request:
      type: string
      format: binary
      
    store_instances_response:
      type: object
    
    retrieve_study_response:
      type: string
      format: binary